import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/componnets/Header";
import Footer from "@/componnets/Footer";
import { Suspense } from "react";
import AboutPage from "./about/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  flex flex-col h-dvh`}
      >
        <Header />
        <div className="grow px-2">{children}</div>
        <Suspense fallback={<div>loading about</div>}>
          <AboutPage />
        </Suspense>
        <Footer />
      </body>
    </html>
  );
}
